### ISSUE TITLE
mount Crono::Web, at: '/crono' fails 

### ISSUE THREAD

**Issue by lgs** [plashchynski/crono#40]
`mount Crono::Web, at: '/crono'` fails  because depending by haml ?

<pre>
$ rails s
=> Booting Thin
=> Rails 4.2.5 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/lsoave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- haml (LoadError)
...
	from /home/lsoave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/crono-0.9.0/lib/crono/web.rb:1:in `<top (required)>'
...
</pre>

**Comment by lgs** [comment]
Ok, this is explained in the [README](https://github.com/plashchynski/crono#web-ui) I didn't see before.
