### ISSUE TITLE
Unknown database 

### ISSUE THREAD

**Issue by assistenzatop** [plashchynski/crono#67]
Hello,
I'm deploying a crono application in production, I've done the installation and migration but crono keeps on returning me an error when I start it: Unknown database ***_dev. 
Of course it's pointing to the DB name in development, while it should point to the production environment, but I haven't found any way to change it. This problem does not affect the Rails application which uses crono, it regurlarly finds and uses the production database, so the problem is not on the database.yml.

bundle exec crono start RAILS_ENV=production
Unknown database '***_dev'

/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:29:in `rescue in mysql2_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:12:in `mysql2_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:442:in `load_schema!'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/attributes.rb:233:in `load_schema!'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/attribute_decorators.rb:28:in `load_schema!'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:437:in `load_schema'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:349:in `attribute_types'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:368:in `type_for_attribute'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/table_metadata.rb:34:in `type'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/predicate_builder.rb:165:in `build_bind_param'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/predicate_builder.rb:124:in `block in create_binds_for_hash'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/predicate_builder.rb:100:in `each'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/predicate_builder.rb:36:in `create_binds'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/where_clause_factory.rb:20:in `build'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/query_methods.rb:632:in `where!'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/query_methods.rb:625:in `where'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation/finder_methods.rb:78:in `find_by'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:224:in `find_or_create_by'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/querying.rb:6:in `find_or_create_by'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/job.rb:114:in `model'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/job.rb:55:in `load'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/scheduler.rb:11:in `add_job'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/performer_proxy.rb:12:in `every'
/home/***/***/config/cronotab.rb:16:in `<top (required)>'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/cronotab.rb:7:in `process'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/lib/crono/cli.rb:29:in `run'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/crono-1.1.2/exe/crono:8:in `<top (required)>'
/home/***/.rbenv/versions/2.4.0/bin/crono:22:in `load'
/home/***/.rbenv/versions/2.4.0/bin/crono:22:in `<top (required)>'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/***/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/***/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/***/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'

Can you please help?

Tnx
Jean

**Comment by assistenzatop** [comment]
OK, I've found the solution:  RAILS_ENV=production bundle exec start crono. It seems the RAILS_ENV should be BEFORE the command. Now it works.
